export const COURCE_LIST_REQUEST = "COURCE_LIST_REQUEST";
export const COURCE_LIST_SUCCESS = "COURCE_LIST_SUCCESS";
export const COURCE_LIST_FAIL = "COURCE_LIST_FAIL";

export const COURCE_CREATE_REQUEST = "COURCE_CREATE_REQUEST";
export const COURCE_CREATE_SUCCESS = "COURCE_CREATE_SUCCESS";
export const COURCE_CREATE_FAIL = "COURCE_CREATE_FAIL";

export const COURCE_UPDATE_REQUEST = "COURCE_UPDATE_REQUEST";
export const COURCE_UPDATE_SUCCESS = "COURCE_UPDATE_SUCCESS";
export const COURCE_UPDATE_FAIL = "COURCE_UPDATE_FAIL";

export const COURCE_DELETE_REQUEST = "COURCE_DELETE_REQUEST";
export const COURCE_DELETE_SUCCESS = "COURCE_DELETE_SUCCESS";
export const COURCE_DELETE_FAIL = "COURCE_DELETE_FAIL";